/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 skull.gltf 
Author: jvitorsouzadesign (https://sketchfab.com/jvitorsouzadesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-salazar-downloadable-eeed09437afb4e1ea8a6ff3b0e9964ad
Title: Skull Salazar (Downloadable)
*/

/**
 * Reference material: https://www.youtube.com/watch?v=M5nt1GamB_g
 */

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const url = `${import.meta.env.BASE_URL}skull.gltf`
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0.019, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Rosa_material} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.defaultMat_material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}skull.gltf`)
